# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow

display_url: https://driveclean-teste.netlify.app

logo_url: https://driveclean.pt/assets/images/favicon.png

locale: "pt"

media_library:
  folder_support: true

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    label_singular: "Publicação"
    description: "Aqui pode ver as publicações que estão no Blog. Pode adicionar uma nova publicação clicando no botão -Nova publicação-. Também pode ordenar por título/data de publicação ou agrupar por ano/identificadores."
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:dsc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      size: "half"
    summary_fields:
      - title
      - date
      - tags
    sortable_fields:
      fields:
        - title
        - date
      default:
        field: date
        direction: Descending
    view_groups:
      groups:
        - label: Ano
          name: year
          field: date
          pattern: \d{4}
        - label: Tags
          name: tags
          field: tags
    preview_path: "/portfolio/{{slug}}"
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Título", name: "title", widget: "string", tagname: "h1" }
      - { label: "Descrição Meta (Aparece nas buscas do Google)", name: "meta_description", widget: "string" }
      - {
          label: "Paragrafo de introdução",
          name: "intro_paragraph",
          widget: "string",
        }
      - name: tags
        label: Tags
        widget: relation
        collection: tags
        search_fields: [title, description]
        value_field: title
        multiple: true
      - {
          label: "Data da Publicação",
          name: "date",
          widget: "datetime",
          format: "yyyy-MM-dd hh:mm:ss",
        }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      - { label: Imagem de capa, name: image, widget: image }
    #teste tags
  - name: tags
    label: Tags
    description: "Aqui pode adicionar/alterar as Tags que aparecem para selecionar nas publicações"
    folder: "_tags"
    slug: "{{slug}}"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "tag" }
      - { name: title, label: Nome }
      - { name: description, label: descrição, widget: text }
    #SITE_SETTINGS
  - name: "site_settings"
    label: "Página HOME"
    description: "Selecione a secção do site que pretende alterar."
    editor:
      preview: false
    files:
      - label: "Cabeçalho"
        name: "header"
        file: "_data/header.yml"
        fields:
          - { label: "Contactos", name: "contact", widget: "string" }
          - {
              label: "Contacto principal (Contacto pré-defenido para ligar)",
              name: "default_contact",
              widget: "string",
            }
      - label: "Banner"
        name: hero
        file: "_data/hero.yml"
        fields:
          - { label: "Título", name: "title", widget: "text" }
          - { label: "Slogan", name: "slogan", widget: "string" }
          - { label: "Link do video", name: "video", widget: "string" }      
          - { label: "Imagem de Fundo", name: "vimage", widget: "image" }
          - label: "Caixa com icon Sabão"
            name: soap
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descrição
                name: description
                widget: string
          - label: "Caixa com icon Escudo"
            name: shield
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descrição
                name: description
                widget: string
          - label: "Caixa com icon Varinha"
            name: stick
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descrição
                name: description
                widget: string
          - label: "Caixa com icon Cuidado"
            name: care
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descrição
                name: description
                widget: string
      - label: "Sobre nós"
        name: aboutus
        file: "_data/aboutus.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "markdown" }
          - { label: "Imagem", name: "backgroundimage", widget: "image" }
          - name: classification
            label: Classificações
            widget: list
            collapsed: true
            label_singular: "Classificação"
            fields:
              - label: Imagem
                name: image
                widget: image
                choose_url: true
              - label: Descrição
                name: description
                widget: string
              - label: Estrelas
                name: stars
                widget: select
                options:
                  - 1
                  - 2
                  - 3
                  - 4
                  - 5
      - label: "Serviços"
        name: services
        file: "_data/services.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "text" }
          - label: "Caixa com icon Vassoura"
            name: vroom
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descrição
                name: description
                widget: string
          - label: "Caixa com icon Sabão"
            name: soap
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descrição
                name: description
                widget: string
          - label: "Caixa com icon Varinha"
            name: stick
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descrição
                name: description
                widget: string
          - label: "Caixa com icon Cuidado"
            name: care
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descrição
                name: description
                widget: string
          - label: "Caixa com icon Spray"
            name: spray
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descrição
                name: description
                widget: string
          - label: "Caixa com icon Chat"
            name: chat
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descrição
                name: description
                widget: string
      - label: "Blog"
        name: blog
        file: "_data/blog.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "text" }
      - label: "Galeria"
        name: gallery
        file: "_data/gallery.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "markdown" }
          - name: images
            label: Galeria
            widget: list
            collapsed: true
            label_singular: "Foto"
            fields:
              - label: Nome
                name: name
                widget: string
              - label: Descrição
                name: description
                widget: string
              - label: Imagem
                name: image
                widget: image
      - label: "Testemunhos"
        name: testemunhos
        file: "_data/testemunhos.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "string" }
          - name: testemunhos
            label: Testemunhos
            widget: list
            collapsed: true
            label_singular: "Testemunho"
            fields:
              - label: Autor
                name: author
                widget: string
              - label: Comentário
                name: comment
                widget: markdown
              - label: Estrelas
                name: stars
                widget: select
                options:
                  - 1
                  - 2
                  - 3
                  - 4
                  - 5
      - label: "Overview"
        name: "overview"
        file: "_data/overview.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: Título, name: title, widget: string}
          - { label: Descrição, name: description, widget: string}
          - {
              label: "Anos de Experiência",
              name: "experience",
              widget: "string",
            }
          - { label: "Serviços efetuados", name: "services", widget: "string" }
          - { label: "Modelos trabalhados", name: "models", widget: "string" }
          - {
              label: "Seguidores Instagram",
              name: "instagram",
              widget: "string",
            }
      - label: "O espaço"
        name: space
        file: "_data/space.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "markdown" }
          - name: images
            label: Fotos
            widget: list
            collapsed: true
            label_singular: "Foto"
            fields:
              - label: Nome
                name: name
                widget: string
              - label: Imagem
                name: image
                widget: image
      ######### TESTE PLANOS ##########
      - label: "Planos"
        name: planos
        description: "Alerar o conteudo da secçao Planos"
        file: "_data/planos.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "markdown" }
          - name: planos
            label: Planos
            collapsed: true
            label_singular: "Plano"
            widget: list
            fields:
              - { name: title, label: Título }
              - { name: value, label: Valor, widget: text }
              - { label: "Descrição", name: "description", widget: "markdown" }
              
      - label: "Serviços externos"
        name: external
        file: "_data/external.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Nº Movel", name: "mobile", widget: "string" }
          - { label: "Nº Fixo", name: "phone", widget: "string" }
          - label: "Serviços"
            name: "services"
            widget: "list"
            label_singular: "Serviço"
            fields:
            - label: "Serviço"
              name: name
              widget: string
      - label: "Rodapé"
        name: "footer"
        file: "_data/footer.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: "Morada Principal", name: "adress", widget: "string" }
          - { label: "2ª Morada", name: "adress2", widget: "string" }
          - { label: "Nº Movel", name: "mobile_number", widget: "string" }
          - { label: "Nº Fixo", name: "office_number", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Descrição", name: "description", widget: text }  
      - label: "Meta Tags"
        name: "meta"
        description: "Adicionar código dentro da secção <head>"
        file: "_data/home_meta.yml"    
        fields:
          - label: 'Código:'
            name: 'home'
            widget: 'code'
            allow_language_selection: true
            default_language: "jsx"


######### PÁGINA DE PERSONALIZAÇÃO ##########
  - name: "personalization"
    label: "Página Personalização"
    description: "Alterar conteudo da página Personalização Automóvel (driveclean.pt/personalização)"
    #editor:
      #preview: false
    files:
      - label: "Conteudo"
        name: "content"
        file: "_data/personalization.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: "Imagem topo", name: hero, widget: image }
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "markdown" }
          - { label: "1ª Imagem", name: image1, widget: image }
          - { label: "2ª Imagem", name: image2, widget: image }
          - label: "Caixa c/info"
            name: box
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descrição
                name: description
                widget: string
          - name: services
            label: Serviços
            collapsed: true
            label_singular: "Serviço"
            widget: list
            fields:
              - { name: title, label: Nome }
              - { label: "Descrição", name: "description", widget: "markdown" }
      - label: "Planos"
        name: planos
        description: "Alerar o conteudo da secçao Planos"
        file: "_data/personalization_planos.yml"
        fields:
          - { label: "Ativo", name: "active", widget: "boolean", default: true }
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "markdown" }
          - name: planos
            label: Planos
            collapsed: true
            label_singular: "Plano"
            widget: list
            fields:
              - { name: title, label: Título }
              - { name: value, label: Valor, widget: text }
              - { label: "Descrição", name: "description", widget: "markdown" }
            

  ######### PÁGINA POLITICA DE COOKIES ##########
  - name: "cookies"
    label: "Página Privacidade"
    description: "Aletar conteudo da página Política de Cookies (driveclean.pt/politica-de-cookies)"
    editor:
      preview: false
    files:
      - label: "Conteudo"
        name: "content"
        file: "_data/cookies.yml"
        fields:
          - { label: "Conteúdo", name: "body", widget: "markdown" }
  
  ######### PÁGINA DE CONTACTO ##########
  - name: "contact"
    label: "Página Contacto"
    description: "Alterar conteudo da página Contacto (driveclean.pt/contact)"
    #editor:
      #preview: false
    files:
      - label: "Conteudo"
        name: "content"
        file: "_data/contact.yml"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "markdown" }
          - name: services
            label: Serviços
            label_singular: "Serviço"
            widget: list
            fields:
              - { name: title, label: Nome }


  